/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHead: typeof import('./src/components/AppHead.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CarbonIcon: typeof import('./src/components/CarbonIcon.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LoginAction: typeof import('./src/components/login/LoginAction.vue')['default']
    MarketingFooter: typeof import('./src/components/MarketingFooter.vue')['default']
    MarketingHeader: typeof import('./src/components/MarketingHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    ToastStack: typeof import('./src/components/ToastStack.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
  }
}
