/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/[locale]': RouteRecordInfo<'/[locale]', '/:locale', { locale: ParamValue<true> }, { locale: ParamValue<false> }, '/[locale]/' | '/[locale]/[...all]' | '/[locale]/hi/[name]'>,
    '/[locale]/': RouteRecordInfo<'/[locale]/', '/:locale', { locale: ParamValue<true> }, { locale: ParamValue<false> }>,
    '/[locale]/[...all]': RouteRecordInfo<'/[locale]/[...all]', '/:locale/:all(.*)', { locale: ParamValue<true>, all: ParamValue<true> }, { locale: ParamValue<false>, all: ParamValue<false> }>,
    '/[locale]/hi/[name]': RouteRecordInfo<'/[locale]/hi/[name]', '/:locale/hi/:name', { locale: ParamValue<true>, name: ParamValue<true> }, { locale: ParamValue<false>, name: ParamValue<false> }>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...all].vue': {
      routes: '/[...all]'
      views: never
    }
    'src/pages/[locale].vue': {
      routes: '/[locale]' | '/[locale]/' | '/[locale]/[...all]' | '/[locale]/hi/[name]' | '/[locale]/hi'
      views: 'default'
    }
    'src/pages/[locale]/index.vue': {
      routes: '/[locale]/'
      views: never
    }
    'src/pages/[locale]/[...all].vue': {
      routes: '/[locale]/[...all]'
      views: never
    }
    'src/pages/[locale]/hi/[name].vue': {
      routes: '/[locale]/hi/[name]'
      views: never
    }
    'src/pages/hi/[name].vue': {
      routes: '/hi/[name]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
